Update Rust fixture cookbook to depend on `toml` crate
We previously depended on the `regex` crate which depends on the `void` crate
which is having compilation issues:

```
Build failed, waiting for other jobs to finish...
           STDERR: /home/kitchen/.cargo/registry/src/github.com-0a35038f75765ae4/void-1.0.2/src/lib.rs:3:35: 3:41 error: no_std is experimental
           /home/kitchen/.cargo/registry/src/github.com-0a35038f75765ae4/void-1.0.2/src/lib.rs:3 #![cfg_attr(not(feature = "std"), no_std)]
                                                                                                                            ^~~~~~
           error: aborting due to previous error
           Could not compile `void`.

           To learn more, run the command again with --verbose.
           ---- End output of cargo build ----
           Ran cargo build returned 101
```

The actual dep we suck in doesn’t matter all that much, we are just
ensuring `cargo build` actually does a thing.